[Interface]
Address = 192.168.100.1/24, 192.168.150.1/24
ListenPort = 51820
PrivateKey = <private-key>
DNS = 192.168.150.40



### NETWORK:-192.168.100.0/24

#web-server
[Peer]
PublicKey =  BcldXboNi466hDyVxMT3PYaYrFxl0TMTL/8lD0UFwg0=
AllowedIPs = 192.168.100.10/32

#web-server
[Peer]
PublicKey =  S0+n9Z+xKWjZQT/V/O0WYMTNeEakKoKGX3OHvRgoAlM=
AllowedIPs = 192.168.100.50/32

#honey-pot
[Peer]
PublicKey = 8LNhj9R48WNu9pijENQZmO8nNnMlBkdL0H6fmyFhfUU=
AllowedIPs = 192.168.100.100/32


### NETWORK:-192.168.150.0/24

#misp
[Peer]
PublicKey = qtUzAco1zMU6iJDPNFKwxh3h3XxeboXvAAgc7Y44ayw=
AllowedIPs = 192.168.150.10/32

#soc-core
[Peer]
PublicKey = jLWN+x/fTo0iTW7+1i2iHT2v56PVNdt30o+ZXWKcAD0=
AllowedIPs = 192.168.150.20/32

#ids
[Peer]
PublicKey = Nt4j5BTvrxCSnd5azc1IGNrrsoW9bR7rNay1MbxNmDo=
AllowedIPs = 192.168.150.30/32

#AD-DS
[Peer]
PublicKey = AvXrV1vXZdfL1tRSHcdZJYNHOiFCwhxWRCQ3LTUXPDM=
AllowedIPs = 192.168.150.40/32
