input {
  http_poller {
    urls => {
      misp_events => {
        method => get
        url => "https://misp.kpk.local/events/index"

        headers => {
          Authorization => "IDYWZKhjT9LVfCOAvKwN45X73QpmcDOLpsIqPb3C"
          Accept => "application/json"
        }
	ssl_verification_mode => "none"
      }
    }

    request_timeout => 60
    schedule => { cron => "*/5 * * * *" }

    codec => "json"
  }
}


filter {
  mutate {
    add_field => {
      "source" => "MISP"
    }
  }
}


output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "misp-threat-intelligence"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
}
