input {
 http_poller {
  urls => {
   misp_iocs => {
    method => post
    url => "https://192.168.150.10/attributes/restSearch"

    headers => {
     Authorization => "IDYWZKhjT9LVfCOAvKwN45X73QpmcDOLpsIqPb3C"
     Accept => "application/json"
     "Content-Type" => "application/json"
    }

    body => '{
     "returnFormat": "json"
     "type": ["ip-dst","domain","url"]
    }'
   }
  }

  request_timeout => 60
  schedule => { cron => "*/10 * * * *" }

  codec => json
 }
}

filter {
 split {
  field => "[response][Attribute]"
 }

 mutate {
  rename => {
   "[response][Attribute][type]" => "[threat][indicator][type]"
   "[response][Attribute][value]" => "[threat][indicator][value]"
  }

  add_field => {
   "[event][dataset]" => "misp.ioc"
   "[event][kind]" => "enrichment"
   "[event][category]" => "threat"
  }
 }
}

output {
 elasticsearch {
  hosts => ["http://elasticsearch:9200"]
  index => "misp-ioc-intelligence"

  user => "elastic"
  password => "${ELASTIC_PASSWORD}"
 }
}
