input {
  http_poller {
    urls => {
      misp_iocs => {
        method => post
        url => "https://misp.kpk.local/attributes/restSearch"

        headers => {
          Authorization => "IDYWZKhjT9LVfCOAvKwN45X73QpmcDOLpsIqPb3C"
          Accept => "application/json"
          "Content-Type" => "application/json"
        }

        body => '{
          "returnFormat": "json",
          "type": [
            "ip-dst",
            "domain",
            "url"
          ],
	  "limit": 100
        }'

	ssl_verification_mode => "none"
      }
    }

    request_timeout => 60
    schedule => { cron => "*/5 * * * *" }

    codec => json
  }
}


filter {
  split {
    field => "[response][Attribute]"
  }


  mutate {

    add_field => {
      "[event][dataset]" => "misp.ioc"
      "[event][kind]" => "enrichment"
      "[event][category]" => "threat"
      "[threat][indicator][provider]" => "MISP"
    }


    rename => {
      "[response][Attribute][type]"  => "[threat][indicator][type]"
      "[response][Attribute][value]" => "[threat][indicator][value]"
    }


    rename => {
      "[response][Attribute][uuid]" => "[threat][indicator][reference]"
    }
  }


  mutate {
    lowercase => [
      "[threat][indicator][type]",
      "[threat][indicator][value]"
    ]
  }
}


output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]

    index => "misp-ioc-intelligence"

    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
}
